#!/usr/bin/env bash

# Set up autograder files



cp /autograder/submission/hw1_1.py /autograder/source/hw1_1.py
cd /autograder/source

cp /autograder/submission/hw1_2.py /autograder/source/hw1_2.py
cd /autograder/source

cp /autograder/submission/hw1_3.py /autograder/source/hw1_3.py
cd /autograder/source

python3 run_tests.py